#!/usr/bin/env node
// Maintains ~/.claude/knowledge-paths.json — the watch list read by
// recall-gate.js --knowledge (knowledge-dossier spec, R15/R17).
//
// Why a script and not a prose instruction: the file is machine-read on the
// hottest tool path. Hand-written JSON drifts (wrong slash direction, missing
// lowercase, a trailing comma) and every such defect is silent — the hook just
// stops firing and nothing says so.
//
// Usage:
//   node knowledge-cache.js set --doc-id 14438 --title "..." --prefix "V:\lib\x.pas" [--prefix ...]
//   node knowledge-cache.js remove --doc-id 14438
//   node knowledge-cache.js list
//   node knowledge-cache.js verify
//
// Exit codes: 0 ok, 1 usage error, 2 write failure. Never fails silently —
// a write that did not happen must not look like one that did.

const fs = require('fs');
const path = require('path');
const os = require('os');

const CACHE = path.join(os.homedir(), '.claude', 'knowledge-paths.json');

function normalisePrefix(p) {
  let s = String(p).replace(/\\/g, '/').toLowerCase().trim();
  // A directory prefix must end in "/" or it would also match a sibling file
  // whose name merely starts with the directory name.
  if (!/\.[a-z0-9]{1,8}$/.test(s) && !s.endsWith('/')) s += '/';
  return s;
}

function load() {
  try {
    if (!fs.existsSync(CACHE)) return { entries: [] };
    const d = JSON.parse(fs.readFileSync(CACHE, 'utf8'));
    return { ...d, entries: Array.isArray(d.entries) ? d.entries : [] };
  } catch (e) {
    // A corrupt cache is reported, never silently replaced: the old content may
    // be the only record of which paths were covered.
    console.error(`[knowledge-cache] existing cache is unreadable: ${e.message}`);
    console.error(`[knowledge-cache] refusing to overwrite ${CACHE} — inspect or delete it first.`);
    process.exit(2);
  }
}

function save(data) {
  data._comment = 'Watch list for recall-gate.js --knowledge. Generated by mxKnowledge from the '
    + 'mandatory "file location" field of each dossier in the _knowledge project (dossier '
    + 'spec R8/R15). Do not edit by hand — run: node knowledge-cache.js set|remove.';
  data._ts = Date.now();
  const tmp = CACHE + '.tmp';
  try {
    fs.mkdirSync(path.dirname(CACHE), { recursive: true });
    fs.writeFileSync(tmp, JSON.stringify(data, null, 2) + '\n', 'utf8');
    fs.renameSync(tmp, CACHE); // atomic: the hook never sees a half-written file
  } catch (e) {
    console.error(`[knowledge-cache] WRITE FAILED: ${e.message}`);
    try { fs.unlinkSync(tmp); } catch { /* best effort */ }
    process.exit(2);
  }
  return true;
}

function argVal(name) {
  const i = process.argv.indexOf(name);
  return i > -1 ? process.argv[i + 1] : undefined;
}
function argVals(name) {
  const out = [];
  process.argv.forEach((a, i) => { if (a === name && process.argv[i + 1]) out.push(process.argv[i + 1]); });
  return out;
}

const cmd = process.argv[2];

if (cmd === 'set') {
  const docId = parseInt(argVal('--doc-id'), 10);
  const title = argVal('--title') || '';
  const prefixes = argVals('--prefix').map(normalisePrefix).filter(Boolean);
  if (!docId || prefixes.length === 0) {
    console.error('usage: set --doc-id <id> --title <t> --prefix <path> [--prefix <path> ...]');
    process.exit(1);
  }
  const data = load();
  data.entries = data.entries.filter(e => e.doc_id !== docId); // replace, never duplicate
  prefixes.forEach(p => data.entries.push({ prefix: p, doc_id: docId, title }));
  save(data);
  console.log(`[knowledge-cache] doc ${docId}: ${prefixes.length} prefix(es) written, ${data.entries.length} total.`);
  prefixes.forEach(p => console.log(`  ${p}`));

} else if (cmd === 'remove') {
  const docId = parseInt(argVal('--doc-id'), 10);
  if (!docId) { console.error('usage: remove --doc-id <id>'); process.exit(1); }
  const data = load();
  const before = data.entries.length;
  data.entries = data.entries.filter(e => e.doc_id !== docId);
  if (before === data.entries.length) {
    console.log(`[knowledge-cache] doc ${docId} was not in the cache — nothing removed.`);
    process.exit(0);
  }
  save(data);
  console.log(`[knowledge-cache] doc ${docId} removed (${before} -> ${data.entries.length}).`);

} else if (cmd === 'list') {
  const data = load();
  if (data.entries.length === 0) { console.log('[knowledge-cache] empty (no dossiers cached).'); process.exit(0); }
  console.log(`[knowledge-cache] ${data.entries.length} entr(ies), written ${new Date(data._ts || 0).toISOString()}:`);
  data.entries.forEach(e => console.log(`  ${e.prefix}  -> #${e.doc_id}  ${e.title || ''}`));

} else if (cmd === 'verify') {
  // Reports prefixes that no longer exist on this machine. NOT an error: a
  // dossier may legitimately cover a path only present on other machines.
  const data = load();
  let missing = 0;
  data.entries.forEach(e => {
    const exists = fs.existsSync(e.prefix);
    if (!exists) { missing++; console.log(`  MISSING ON THIS MACHINE: ${e.prefix} (#${e.doc_id})`); }
  });
  console.log(`[knowledge-cache] ${data.entries.length} entr(ies), ${missing} not present locally.`);

} else {
  console.error('usage: knowledge-cache.js set|remove|list|verify [...]');
  process.exit(1);
}
